
export const stationData = [
  {
    stn_code: 'NS1',
    mrt_station_english: 'Jurong East',
    mrt_station_chinese: '裕廊东',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'yu lang dong',
    abbreviation: 'JUR',
  },
  {
    stn_code: 'NS2',
    mrt_station_english: 'Bukit Batok',
    mrt_station_chinese: '武吉巴督',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'wu ji ba du',
    abbreviation: 'BBT',
  },
  {
    stn_code: 'NS3',
    mrt_station_english: 'Bukit Gombak',
    mrt_station_chinese: '武吉甘柏',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'wu ji gan bai',
    abbreviation: 'BGB',
  },
  {
    stn_code: 'NS4',
    mrt_station_english: 'Choa Chu Kang',
    mrt_station_chinese: '蔡厝港',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'cai cuo gang',
    abbreviation: 'CCK',
  },
  {
    stn_code: 'NS5',
    mrt_station_english: 'Yew Tee',
    mrt_station_chinese: '油池',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'you chi',
    abbreviation: 'YWT',
  },
  {
    stn_code: 'NS7',
    mrt_station_english: 'Kranji',
    mrt_station_chinese: '克兰芝',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'ke lan zhi',
    abbreviation: 'KRJ',
  },
  {
    stn_code: 'NS8',
    mrt_station_english: 'Marsiling',
    mrt_station_chinese: '马西岭',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'ma xi ling',
    abbreviation: 'MSL',
  },
  {
    stn_code: 'NS9',
    mrt_station_english: 'Woodlands',
    mrt_station_chinese: '兀兰',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'wu lan',
    abbreviation: 'WDL',
  },
  {
    stn_code: 'NS10',
    mrt_station_english: 'Admiralty',
    mrt_station_chinese: '海军部',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'hai jun bu',
    abbreviation: 'ADM',
  },
  {
    stn_code: 'NS11',
    mrt_station_english: 'Sembawang',
    mrt_station_chinese: '三巴旺',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'san ba wang',
    abbreviation: 'SBW',
  },
  {
    stn_code: 'NS13',
    mrt_station_english: 'Yishun',
    mrt_station_chinese: '义顺',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'yi shun',
    abbreviation: 'YIS',
  },
  {
    stn_code: 'NS14',
    mrt_station_english: 'Khatib',
    mrt_station_chinese: '卡迪',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'ka di',
    abbreviation: 'KTB',
  },
  {
    stn_code: 'NS15',
    mrt_station_english: 'Yio Chu Kang',
    mrt_station_chinese: '杨厝港',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'yang cuo gang',
    abbreviation: 'YCK',
  },
  {
    stn_code: 'NS16',
    mrt_station_english: 'Ang Mo Kio',
    mrt_station_chinese: '宏茂桥',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'hong mao qiao',
    abbreviation: 'AMK',
  },
  {
    stn_code: 'NS17',
    mrt_station_english: 'Bishan',
    mrt_station_chinese: '碧山',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'bi shan',
    abbreviation: 'BSH',
  },
  {
    stn_code: 'NS18',
    mrt_station_english: 'Braddell',
    mrt_station_chinese: '布莱德',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'bu lai de',
    abbreviation: 'BDL',
  },
  {
    stn_code: 'NS19',
    mrt_station_english: 'Toa Payoh',
    mrt_station_chinese: '大巴窑',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'da ba yao',
    abbreviation: 'TAP',
  },
  {
    stn_code: 'NS20',
    mrt_station_english: 'Novena',
    mrt_station_chinese: '诺维娜',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'nuo wei na',
    abbreviation: 'NOV',
  },
  {
    stn_code: 'NS21',
    mrt_station_english: 'Newton',
    mrt_station_chinese: '纽顿',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'niu dun',
    abbreviation: 'NEW',
  },
  {
    stn_code: 'NS22',
    mrt_station_english: 'Orchard',
    mrt_station_chinese: '乌节',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'wu jie',
    abbreviation: 'ORC',
  },
  {
    stn_code: 'NS23',
    mrt_station_english: 'Somerset',
    mrt_station_chinese: '索美塞',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'suo mei se',
    abbreviation: 'SOM',
  },
  {
    stn_code: 'NS24',
    mrt_station_english: 'Dhoby Ghaut',
    mrt_station_chinese: '多美歌',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'duo mei ge',
    abbreviation: 'DBG',
  },
  {
    stn_code: 'NS25',
    mrt_station_english: 'City Hall',
    mrt_station_chinese: '政府大厦',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'zheng fu da xia',
    abbreviation: 'CTH',
  },
  {
    stn_code: 'NS26',
    mrt_station_english: 'Raffles Place',
    mrt_station_chinese: '莱佛士坊',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'lai fo shi fang',
    abbreviation: 'RFP',
  },
  {
    stn_code: 'NS27',
    mrt_station_english: 'Marina Bay',
    mrt_station_chinese: '滨海湾',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'bin hai wan',
    abbreviation: 'MRB',
  },
  {
    stn_code: 'NS28',
    mrt_station_english: 'Marina South Pier',
    mrt_station_chinese: '滨海南码头',
    mrt_line_english: 'North South Line',
    mrt_line_chinese: '南北线',
    mrt_station_pinyin: 'bin hai nan ma tou',
    abbreviation: 'MSP',
  },
  {
    stn_code: 'EW1',
    mrt_station_english: 'Pasir Ris',
    mrt_station_chinese: '巴西立',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'ba xi li',
    abbreviation: 'PSR',
  },
  {
    stn_code: 'EW2',
    mrt_station_english: 'Tampines',
    mrt_station_chinese: '淡滨尼',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'dan bin ni',
    abbreviation: 'TAM',
  },
  {
    stn_code: 'EW3',
    mrt_station_english: 'Simei',
    mrt_station_chinese: '四美',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'si mei',
    abbreviation: 'SIM',
  },
  {
    stn_code: 'EW4',
    mrt_station_english: 'Tanah Merah',
    mrt_station_chinese: '丹那美拉',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'dan na mei la',
    abbreviation: 'TNM',
  },
  {
    stn_code: 'EW5',
    mrt_station_english: 'Bedok',
    mrt_station_chinese: '勿洛',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'wu luo',
    abbreviation: 'BDK',
  },
  {
    stn_code: 'EW6',
    mrt_station_english: 'Kembangan',
    mrt_station_chinese: '景万岸',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'jing wan an',
    abbreviation: 'KEM',
  },
  {
    stn_code: 'EW7',
    mrt_station_english: 'Eunos',
    mrt_station_chinese: '友诺士',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'you nuo shi',
    abbreviation: 'EUN',
  },
  {
    stn_code: 'EW8',
    mrt_station_english: 'Paya Lebar',
    mrt_station_chinese: '巴耶利峇',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'ba ye li ba',
    abbreviation: 'PYL',
  },
  {
    stn_code: 'EW9',
    mrt_station_english: 'Aljunied',
    mrt_station_chinese: '阿裕尼',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'a yu ni',
    abbreviation: 'ALJ',
  },
  {
    stn_code: 'EW10',
    mrt_station_english: 'Kallang',
    mrt_station_chinese: '加冷',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'jia leng',
    abbreviation: 'KAL',
  },
  {
    stn_code: 'EW11',
    mrt_station_english: 'Lavender',
    mrt_station_chinese: '劳明达',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'lao ming da',
    abbreviation: 'LAV',
  },
  {
    stn_code: 'EW12',
    mrt_station_english: 'Bugis',
    mrt_station_chinese: '武吉士',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'wu ji shi',
    abbreviation: 'BUG',
  },
  {
    stn_code: 'EW13',
    mrt_station_english: 'City Hall',
    mrt_station_chinese: '政府大厦',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'zheng fu da xia',
    abbreviation: 'CTH',
  },
  {
    stn_code: 'EW14',
    mrt_station_english: 'Raffles Place',
    mrt_station_chinese: '莱佛士坊',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'lai fo shi fang',
    abbreviation: 'RFP',
  },
  {
    stn_code: 'EW15',
    mrt_station_english: 'Tanjong Pagar',
    mrt_station_chinese: '丹戎巴葛',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'dan rong ba ge',
    abbreviation: 'TGP',
  },
  {
    stn_code: 'EW16',
    mrt_station_english: 'Outram Park',
    mrt_station_chinese: '欧南园',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'ou nan yuan',
    abbreviation: 'OTP',
  },
  {
    stn_code: 'EW17',
    mrt_station_english: 'Tiong Bahru',
    mrt_station_chinese: '中峇鲁',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'zhong ba lu',
    abbreviation: 'TBH',
  },
  {
    stn_code: 'EW18',
    mrt_station_english: 'Redhill',
    mrt_station_chinese: '红山',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'hong shan',
    abbreviation: 'RDH',
  },
  {
    stn_code: 'EW19',
    mrt_station_english: 'Queenstown',
    mrt_station_chinese: '女皇镇',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'nu huang zhen',
    abbreviation: 'QTN',
  },
  {
    stn_code: 'EW20',
    mrt_station_english: 'Commonwealth',
    mrt_station_chinese: '联邦',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'lian bang',
    abbreviation: 'COM',
  },
  {
    stn_code: 'EW21',
    mrt_station_english: 'Buona Vista',
    mrt_station_chinese: '波那维斯达',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'bo na wei si da',
    abbreviation: 'BNV',
  },
  {
    stn_code: 'EW22',
    mrt_station_english: 'Dover',
    mrt_station_chinese: '杜弗',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'du fu',
    abbreviation: 'DVR',
  },
  {
    stn_code: 'EW23',
    mrt_station_english: 'Clementi',
    mrt_station_chinese: '金文泰',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'jin wen tai',
    abbreviation: 'CLE',
  },
  {
    stn_code: 'EW24',
    mrt_station_english: 'Jurong East',
    mrt_station_chinese: '裕廊东',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'yu lang dong',
    abbreviation: 'JUR',
  },
  {
    stn_code: 'EW25',
    mrt_station_english: 'Chinese Garden',
    mrt_station_chinese: '裕华园',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'yu hua yuan',
    abbreviation: 'CGD',
  },
  {
    stn_code: 'EW26',
    mrt_station_english: 'Lakeside',
    mrt_station_chinese: '湖畔',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'hu pan',
    abbreviation: 'LKS',
  },
  {
    stn_code: 'EW27',
    mrt_station_english: 'Boon Lay',
    mrt_station_chinese: '文礼',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'wen li',
    abbreviation: 'BNL',
  },
  {
    stn_code: 'EW28',
    mrt_station_english: 'Pioneer',
    mrt_station_chinese: '先驱',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'xian qu',
    abbreviation: 'PNR',
  },
  {
    stn_code: 'EW29',
    mrt_station_english: 'Joo Koon',
    mrt_station_chinese: '裕群',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'yu qun',
    abbreviation: 'JKN',
  },
  {
    stn_code: 'EW30',
    mrt_station_english: 'Gul Circle',
    mrt_station_chinese: '卡尔圈站',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'ka er quan zhan',
    abbreviation: 'GUL',
  },
  {
    stn_code: 'EW31',
    mrt_station_english: 'Tuas Crescent',
    mrt_station_chinese: '大士弯站',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'da shi wan zhan',
    abbreviation: 'TCR',
  },
  {
    stn_code: 'EW32',
    mrt_station_english: 'Tuas West Road',
    mrt_station_chinese: '大士西路站',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'da shi xi lu zhan',
    abbreviation: 'TWR',
  },
  {
    stn_code: 'EW33',
    mrt_station_english: 'Tuas Link',
    mrt_station_chinese: '大士连路站',
    mrt_line_english: 'East West Line',
    mrt_line_chinese: '东西线',
    mrt_station_pinyin: 'da shi lian lu zhan',
    abbreviation: 'TLK',
  },
  {
    stn_code: 'CG1',
    mrt_station_english: 'Expo',
    mrt_station_chinese: '博览',
    mrt_line_english: 'Changi Airport Branch Line',
    mrt_line_chinese: '樟宜机场支线',
    mrt_station_pinyin: 'bo lan',
    abbreviation: 'EXC',
  },
  {
    stn_code: 'CG2',
    mrt_station_english: 'Changi Airport',
    mrt_station_chinese: '樟宜机场',
    mrt_line_english: 'Changi Airport Branch Line',
    mrt_line_chinese: '樟宜机场支线',
    mrt_station_pinyin: 'zhang yi ji chang',
    abbreviation: 'CGA',
  },
  {
    stn_code: 'NE1',
    mrt_station_english: 'HarbourFront',
    mrt_station_chinese: '港湾',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'gang wan',
    abbreviation: 'HBF',
  },
  {
    stn_code: 'NE3',
    mrt_station_english: 'Outram Park',
    mrt_station_chinese: '欧南园',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'ou nan yuan',
    abbreviation: 'OTP',
  },
  {
    stn_code: 'NE4',
    mrt_station_english: 'Chinatown',
    mrt_station_chinese: '牛车水',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'niu che shui',
    abbreviation: 'CNT',
  },
  {
    stn_code: 'NE5',
    mrt_station_english: 'Clarke Quay',
    mrt_station_chinese: '克拉码头',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'ke la ma tou',
    abbreviation: 'CQY',
  },
  {
    stn_code: 'NE6',
    mrt_station_english: 'Dhoby Ghaut',
    mrt_station_chinese: '多美歌',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'duo mei ge',
    abbreviation: 'DBG',
  },
  {
    stn_code: 'NE7',
    mrt_station_english: 'Little India',
    mrt_station_chinese: '小印度',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'xiao yin du',
    abbreviation: 'LTI',
  },
  {
    stn_code: 'NE8',
    mrt_station_english: 'Farrer Park',
    mrt_station_chinese: '花拉公园',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'hua la gong yuan',
    abbreviation: 'FRP',
  },
  {
    stn_code: 'NE9',
    mrt_station_english: 'Boon Keng',
    mrt_station_chinese: '文庆',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'wen qing',
    abbreviation: 'BNK',
  },
  {
    stn_code: 'NE10',
    mrt_station_english: 'Potong Pasir',
    mrt_station_chinese: '波东巴西',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'bo dong ba xi',
    abbreviation: 'PTP',
  },
  {
    stn_code: 'NE11',
    mrt_station_english: 'Woodleigh',
    mrt_station_chinese: '兀里',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'wu li',
    abbreviation: 'WDL',
  },
  {
    stn_code: 'NE12',
    mrt_station_english: 'Serangoon',
    mrt_station_chinese: '实龙岗',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'shi long gang',
    abbreviation: 'SER',
  },
  {
    stn_code: 'NE13',
    mrt_station_english: 'Kovan',
    mrt_station_chinese: '高文',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'gao wen',
    abbreviation: 'KOV',
  },
  {
    stn_code: 'NE14',
    mrt_station_english: 'Hougang',
    mrt_station_chinese: '后港',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'hou gang',
    abbreviation: 'HGN',
  },
  {
    stn_code: 'NE15',
    mrt_station_english: 'Buangkok',
    mrt_station_chinese: '万国',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'wan guo',
    abbreviation: 'BGK',
  },
  {
    stn_code: 'NE16',
    mrt_station_english: 'Sengkang',
    mrt_station_chinese: '盛港',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'sheng gang',
    abbreviation: 'SKG',
  },
  {
    stn_code: 'NE17',
    mrt_station_english: 'Punggol',
    mrt_station_chinese: '榜鹅',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'bang e',
    abbreviation: 'PGL',
  },
  {
    stn_code: 'NE18',
    mrt_station_english: 'Punggol Coast',
    mrt_station_chinese: '榜鹅海岸',
    mrt_line_english: 'North East Line',
    mrt_line_chinese: '东北线',
    mrt_station_pinyin: 'bang e hai an',
    abbreviation: 'PGC',
  },
  {
    stn_code: 'CC1',
    mrt_station_english: 'Dhoby Ghaut',
    mrt_station_chinese: '多美歌',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'duo mei ge',
    abbreviation: 'DBG',
  },
  {
    stn_code: 'CC2',
    mrt_station_english: 'Bras Basah',
    mrt_station_chinese: '百胜',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'bai sheng',
    abbreviation: 'BSB',
  },
  {
    stn_code: 'CC3',
    mrt_station_english: 'Esplanade',
    mrt_station_chinese: '滨海中心',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'bin hai zhong xin',
    abbreviation: 'ESP',
  },
  {
    stn_code: 'CC4',
    mrt_station_english: 'Promenade',
    mrt_station_chinese: '宝门廊',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'bao men lang',
    abbreviation: 'PMN',
  },
  {
    stn_code: 'CC5',
    mrt_station_english: 'Nicoll Highway',
    mrt_station_chinese: '尼诰大道',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ni gao da dao',
    abbreviation: 'NCH',
  },
  {
    stn_code: 'CC6',
    mrt_station_english: 'Stadium',
    mrt_station_chinese: '体育场',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ti yu chang',
    abbreviation: 'STA',
  },
  {
    stn_code: 'CC7',
    mrt_station_english: 'Mountbatten',
    mrt_station_chinese: '蒙巴登',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'meng ba deng',
    abbreviation: 'MBT',
  },
  {
    stn_code: 'CC8',
    mrt_station_english: 'Dakota',
    mrt_station_chinese: '达科达',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'da ke da',
    abbreviation: 'DKT',
  },
  {
    stn_code: 'CC9',
    mrt_station_english: 'Paya Lebar',
    mrt_station_chinese: '巴耶利峇',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ba ye li ba',
    abbreviation: 'PYL',
  },
  {
    stn_code: 'CC10',
    mrt_station_english: 'MacPherson',
    mrt_station_chinese: '麦波申',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'mai bo shen',
    abbreviation: 'MPS',
  },
  {
    stn_code: 'CC11',
    mrt_station_english: 'Tai Seng',
    mrt_station_chinese: '大成',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'da cheng',
    abbreviation: 'TSG',
  },
  {
    stn_code: 'CC12',
    mrt_station_english: 'Bartley',
    mrt_station_chinese: '巴特礼',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ba te li',
    abbreviation: 'BTL',
  },
  {
    stn_code: 'CC13',
    mrt_station_english: 'Serangoon',
    mrt_station_chinese: '实龙岗',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'shi long gang',
    abbreviation: 'SER',
  },
  {
    stn_code: 'CC14',
    mrt_station_english: 'Lorong Chuan',
    mrt_station_chinese: '罗弄泉',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'luo nong quan',
    abbreviation: 'LRC',
  },
  {
    stn_code: 'CC15',
    mrt_station_english: 'Bishan',
    mrt_station_chinese: '碧山',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'bi shan',
    abbreviation: 'BSH',
  },
  {
    stn_code: 'CC16',
    mrt_station_english: 'Marymount',
    mrt_station_chinese: '玛丽蒙',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ma li meng',
    abbreviation: 'MRM',
  },
  {
    stn_code: 'CC17',
    mrt_station_english: 'Caldecott',
    mrt_station_chinese: '加利谷',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'jia li gu',
    abbreviation: 'CDT',
  },
  {
    stn_code: 'CC19',
    mrt_station_english: 'Botanic Gardens',
    mrt_station_chinese: '植物园',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'zhi wu yuan',
    abbreviation: 'BTG',
  },
  {
    stn_code: 'CC20',
    mrt_station_english: 'Farrer Road',
    mrt_station_chinese: '花拉路',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'hua la lu',
    abbreviation: 'FRR',
  },
  {
    stn_code: 'CC21',
    mrt_station_english: 'Holland Village',
    mrt_station_chinese: '荷兰村',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'he lan cun',
    abbreviation: 'HDV',
  },
  {
    stn_code: 'CC22',
    mrt_station_english: 'Buona Vista',
    mrt_station_chinese: '波那维斯达',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'bo na wei si da',
    abbreviation: 'BNV',
  },
  {
    stn_code: 'CC23',
    mrt_station_english: 'one-north',
    mrt_station_chinese: '纬壹',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'wei yi',
    abbreviation: 'ONH',
  },
  {
    stn_code: 'CC24',
    mrt_station_english: 'Kent Ridge',
    mrt_station_chinese: '肯特岗',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ken te gang',
    abbreviation: 'KRG',
  },
  {
    stn_code: 'CC25',
    mrt_station_english: 'Haw Par Villa',
    mrt_station_chinese: '虎豹别墅',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'hu bao bie shu',
    abbreviation: 'HPV',
  },
  {
    stn_code: 'CC26',
    mrt_station_english: 'Pasir Panjang',
    mrt_station_chinese: '巴西班让',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'ba xi ban rang',
    abbreviation: 'PPJ',
  },
  {
    stn_code: 'CC27',
    mrt_station_english: 'Labrador Park',
    mrt_station_chinese: '拉柏多公园',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'la bo duo gong yuan',
    abbreviation: 'LBD',
  },
  {
    stn_code: 'CC28',
    mrt_station_english: 'Telok Blangah',
    mrt_station_chinese: '直落布兰雅',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'zhi luo bu lan ya',
    abbreviation: 'TKG',
  },
  {
    stn_code: 'CC29',
    mrt_station_english: 'HarbourFront',
    mrt_station_chinese: '港湾',
    mrt_line_english: 'Circle Line',
    mrt_line_chinese: '环线',
    mrt_station_pinyin: 'gang wan',
    abbreviation: 'HBF',
  },
  {
    stn_code: 'CE1',
    mrt_station_english: 'Bayfront',
    mrt_station_chinese: '海湾舫',
    mrt_line_english: 'Circle Line Extension',
    mrt_line_chinese: '环线延长线',
    mrt_station_pinyin: 'hai wan fang',
    abbreviation: 'BFT',
  },
  {
    stn_code: 'CE2',
    mrt_station_english: 'Marina Bay',
    mrt_station_chinese: '滨海湾',
    mrt_line_english: 'Circle Line Extension',
    mrt_line_chinese: '环线延长线',
    mrt_station_pinyin: 'bin hai wan',
    abbreviation: 'MRB',
  },
  {
    stn_code: 'DT1',
    mrt_station_english: 'Bukit Panjang',
    mrt_station_chinese: '武吉班让',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'wu ji ban rang',
    abbreviation: 'BPJ',
  },
  {
    stn_code: 'DT2',
    mrt_station_english: 'Cashew',
    mrt_station_chinese: '凯秀',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'kai xiu',
    abbreviation: 'CSW',
  },
  {
    stn_code: 'DT3',
    mrt_station_english: 'Hillview',
    mrt_station_chinese: '山景',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'shan jing',
    abbreviation: 'HVW',
  },
  {
    stn_code: 'DT4',
    mrt_station_english: 'Hume',
    mrt_station_chinese: '谦道',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'qian dao',
    abbreviation: 'HME',
  },
  {
    stn_code: 'DT5',
    mrt_station_english: 'Beauty World',
    mrt_station_chinese: '美世界',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'mei shi jie',
    abbreviation: 'BTW',
  },
  {
    stn_code: 'DT6',
    mrt_station_english: 'King Albert Park',
    mrt_station_chinese: '阿尔柏王园',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'a er bai wang yuan',
    abbreviation: 'KAP',
  },
  {
    stn_code: 'DT7',
    mrt_station_english: 'Sixth Avenue',
    mrt_station_chinese: '第六道',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'di liu dao',
    abbreviation: 'SVA',
  },
  {
    stn_code: 'DT8',
    mrt_station_english: 'Tan Kah Kee',
    mrt_station_chinese: '陈嘉庚',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
mrt_station_pinyin: 'chen jia geng',
    abbreviation: 'TKK',
  },
  {
    stn_code: 'DT9',
    mrt_station_english: 'Botanic Gardens',
    mrt_station_chinese: '植物园',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'zhi wu yuan',
    abbreviation: 'BTG',
  },
  {
    stn_code: 'DT10',
    mrt_station_english: 'Stevens',
    mrt_station_chinese: '史蒂芬',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'shi di fen',
    abbreviation: 'STV',
  },
  {
    stn_code: 'DT11',
    mrt_station_english: 'Newton',
    mrt_station_chinese: '纽顿',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'niu dun',
    abbreviation: 'NEW',
  },
  {
    stn_code: 'DT12',
    mrt_station_english: 'Little India',
    mrt_station_chinese: '小印度',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'xiao yin du',
    abbreviation: 'LTI',
  },
  {
    stn_code: 'DT13',
    mrt_station_english: 'Rochor',
    mrt_station_chinese: '梧槽',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'wu cao',
    abbreviation: 'RCR',
  },
  {
    stn_code: 'DT14',
    mrt_station_english: 'Bugis',
    mrt_station_chinese: '武吉士',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'wu ji shi',
    abbreviation: 'BUG',
  },
  {
    stn_code: 'DT15',
    mrt_station_english: 'Promenade',
    mrt_station_chinese: '宝门廊',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'bao men lang',
    abbreviation: 'PMN',
  },
  {
    stn_code: 'DT16',
    mrt_station_english: 'Bayfront',
    mrt_station_chinese: '海湾舫',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'hai wan fang',
    abbreviation: 'BFT',
  },
  {
    stn_code: 'DT17',
    mrt_station_english: 'Downtown',
    mrt_station_chinese: '市中心',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'shi zhong xin',
    abbreviation: 'DTN',
  },
  {
    stn_code: 'DT18',
    mrt_station_english: 'Telok Ayer',
    mrt_station_chinese: '直落亚逸',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'zhi luo ya yi',
    abbreviation: 'TLA',
  },
  {
    stn_code: 'DT19',
    mrt_station_english: 'Chinatown',
    mrt_station_chinese: '牛车水',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'niu che shui',
    abbreviation: 'CNT',
  },
  {
    stn_code: 'DT20',
    mrt_station_english: 'Fort Canning',
    mrt_station_chinese: '福康宁',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'fu kang ning',
    abbreviation: 'FCN',
  },
  {
    stn_code: 'DT21',
    mrt_station_english: 'Bencoolen',
    mrt_station_chinese: '明古连',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'ming gu lian',
    abbreviation: 'BCL',
  },
  {
    stn_code: 'DT22',
    mrt_station_english: 'Jalan Besar',
    mrt_station_chinese: '惹兰勿刹',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 're lan wu sha',
    abbreviation: 'JLB',
  },
  {
    stn_code: 'DT23',
    mrt_station_english: 'Bendemeer',
    mrt_station_chinese: '明地迷亚',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'ming di mi ya',
    abbreviation: 'BDM',
  },
  {
    stn_code: 'DT24',
    mrt_station_english: 'Geylang Bahru',
    mrt_station_chinese: '芽笼峇鲁',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'ya long ba lu',
    abbreviation: 'GLB',
  },
  {
    stn_code: 'DT25',
    mrt_station_english: 'Mattar',
    mrt_station_chinese: '玛达',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'ma da',
    abbreviation: 'MTR',
  },
  {
    stn_code: 'DT26',
    mrt_station_english: 'MacPherson',
    mrt_station_chinese: '麦波申',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'mai bo shen',
    abbreviation: 'MPS',
  },
  {
    stn_code: 'DT27',
    mrt_station_english: 'Ubi',
    mrt_station_chinese: '乌美',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'wu mei',
    abbreviation: 'UBI',
  },
  {
    stn_code: 'DT28',
    mrt_station_english: 'Kaki Bukit',
    mrt_station_chinese: '加基武吉',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'jia ji wu ji',
    abbreviation: 'KKB',
  },
  {
    stn_code: 'DT29',
    mrt_station_english: 'Bedok North',
    mrt_station_chinese: '勿洛北',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'wu luo bei',
    abbreviation: 'BDN',
  },
  {
    stn_code: 'DT30',
    mrt_station_english: 'Bedok Reservoir',
    mrt_station_chinese: '勿洛蓄水池',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'wu luo xu shui chi',
    abbreviation: 'BDR',
  },
  {
    stn_code: 'DT31',
    mrt_station_english: 'Tampines West',
    mrt_station_chinese: '淡滨尼西',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'dan bin ni xi',
    abbreviation: 'TPW',
  },
  {
    stn_code: 'DT32',
    mrt_station_english: 'Tampines',
    mrt_station_chinese: '淡滨尼',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'dan bin ni',
    abbreviation: 'TAM',
  },
  {
    stn_code: 'DT33',
    mrt_station_english: 'Tampines East',
    mrt_station_chinese: '淡滨尼东',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'dan bin ni dong',
    abbreviation: 'TPE',
  },
  {
    stn_code: 'DT34',
    mrt_station_english: 'Upper Changi',
    mrt_station_chinese: '樟宜上段',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'zhang yi shang duan',
    abbreviation: 'UPC',
  },
  {
    stn_code: 'DT35',
    mrt_station_english: 'Expo',
    mrt_station_chinese: '博览',
    mrt_line_english: 'Downtown Line',
    mrt_line_chinese: '滨海市区线',
    mrt_station_pinyin: 'bo lan',
    abbreviation: 'EXC',
  },
  {
    stn_code: 'TE1',
    mrt_station_english: 'Woodlands North',
    mrt_station_chinese: '兀兰北',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'wu lan bei',
    abbreviation: 'Wdn',
  },
  {
    stn_code: 'TE2',
    mrt_station_english: 'Woodlands',
    mrt_station_chinese: '兀兰',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'wu lan',
    abbreviation: 'WDL',
  },
  {
    stn_code: 'TE3',
    mrt_station_english: 'Woodlands South',
    mrt_station_chinese: '兀兰南',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'wu lan nan',
    abbreviation: 'WDS',
  },
  {
    stn_code: 'TE4',
    mrt_station_english: 'Springleaf',
    mrt_station_chinese: '春叶',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'chun ye',
    abbreviation: 'SPL',
  },
  {
    stn_code: 'TE5',
    mrt_station_english: 'Lentor',
    mrt_station_chinese: '伦多',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'lun duo',
    abbreviation: 'LTR',
  },
  {
    stn_code: 'TE6',
    mrt_station_english: 'Mayflower',
    mrt_station_chinese: '美华',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'mei hua',
    abbreviation: 'MYF',
  },
  {
    stn_code: 'TE7',
    mrt_station_english: 'Bright Hill',
    mrt_station_chinese: '光明山',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'guang ming shan',
    abbreviation: 'BRH',
  },
  {
    stn_code: 'TE8',
    mrt_station_english: 'Upper Thomson',
    mrt_station_chinese: '汤申路上段',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'tang shen lu shang duan',
    abbreviation: 'UTH',
  },
  {
    stn_code: 'TE9',
    mrt_station_english: 'Caldecott',
    mrt_station_chinese: '加利谷',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'jia li gu',
    abbreviation: 'CDT',
  },
  {
    stn_code: 'TE10',
    mrt_station_english: 'Mount Pleasant',
    mrt_station_chinese: '快乐山',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'kuai le shan',
    abbreviation: 'MPL',
  },
  {
    stn_code: 'TE11',
    mrt_station_english: 'Stevens',
    mrt_station_chinese: '史蒂芬',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'shi di fen',
    abbreviation: 'STV',
  },
  {
    stn_code: 'TE12',
    mrt_station_english: 'Napier',
    mrt_station_chinese: '纳比雅',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'na bi ya',
    abbreviation: 'NPR',
  },
  {
    stn_code: 'TE13',
    mrt_station_english: 'Orchard Boulevard',
    mrt_station_chinese: '乌节大道',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'wu jie da dao',
    abbreviation: 'OBV',
  },
  {
    stn_code: 'TE14',
    mrt_station_english: 'Orchard',
    mrt_station_chinese: '乌节',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'wu jie',
    abbreviation: 'ORC',
  },
  {
    stn_code: 'TE15',
    mrt_station_english: 'Great World',
    mrt_station_chinese: '大世界',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'da shi jie',
    abbreviation: 'GRW',
  },
  {
    stn_code: 'TE16',
    mrt_station_english: 'Havelock',
    mrt_station_chinese: '合乐',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'he le',
    abbreviation: 'HVL',
  },
  {
    stn_code: 'TE17',
    mrt_station_english: 'Outram Park',
    mrt_station_chinese: '欧南园',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'ou nan yuan',
    abbreviation: 'OTP',
  },
  {
    stn_code: 'TE18',
    mrt_station_english: 'Maxwell',
    mrt_station_chinese: '麦士威',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'mai shi wei',
    abbreviation: 'MXW',
  },
  {
    stn_code: 'TE19',
    mrt_station_english: 'Shenton Way',
    mrt_station_chinese: '珊顿道',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'shan dun dao',
    abbreviation: 'STW',
  },
  {
    stn_code: 'TE20',
    mrt_station_english: 'Marina Bay',
    mrt_station_chinese: '滨海湾',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'bin hai wan',
    abbreviation: 'MRB',
  },
  {
    stn_code: 'TE21',
    mrt_station_english: 'Marina South',
    mrt_station_chinese: '滨海南',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'bin hai nan',
    abbreviation: 'MRS',
  },
  {
    stn_code: 'TE22',
    mrt_station_english: 'Gardens by the Bay',
    mrt_station_chinese: '滨海湾花园',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'bin hai wan hua yuan',
    abbreviation: 'GBY',
  },
  {
    stn_code: 'TE22A',
    mrt_station_english: "Founders' Memorial",
    mrt_station_chinese: '建国先贤纪念园',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'jian guo xian xian ji nian yuan',
    abbreviation: 'FDM',
  },
  {
    stn_code: 'TE23',
    mrt_station_english: 'Tanjong Rhu',
    mrt_station_chinese: '丹戎禺',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'dan rong yu',
    abbreviation: 'TJR',
  },
  {
    stn_code: 'TE24',
    mrt_station_english: 'Katong Park',
    mrt_station_chinese: '加东公园',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'jia dong gong yuan',
    abbreviation: 'KTP',
  },
  {
    stn_code: 'TE25',
    mrt_station_english: 'Tanjong Katong',
    mrt_station_chinese: '丹戎加东',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'dan rong jia dong',
    abbreviation: 'TJK',
  },
  {
    stn_code: 'TE26',
    mrt_station_english: 'Marine Parade',
    mrt_station_chinese: '马林百列',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'ma lin bai lie',
    abbreviation: 'MPD',
  },
  {
    stn_code: 'TE27',
    mrt_station_english: 'Marine Terrace',
    mrt_station_chinese: '马林台',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'ma lin tai',
    abbreviation: 'MTE',
  },
  {
    stn_code: 'TE28',
    mrt_station_english: 'Siglap',
    mrt_station_chinese: '实乞纳',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'shi qi na',
    abbreviation: 'SGP',
  },
  {
    stn_code: 'TE29',
    mrt_station_english: 'Bayshore',
    mrt_station_chinese: '碧湾',
    mrt_line_english: 'Thomson-East Coast Line',
    mrt_line_chinese: '汤申-东海岸线',
    mrt_station_pinyin: 'bi wan',
    abbreviation: 'BSH',
  },
];

    